### ISSUE TITLE
smard.de. Doesn't work anymore since 02.09.24

### ISSUE THREAD

**Issue by Menelmacar** [mampfes/ha_epex_spot#147] opened 2024-09-03 09:05 UTC
Every entity not available anymore. Is it just me or did they change something for example?

**Comment by Menelmacar** [comment] 2024-09-03 09:10
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.epex_spot.SourceShell
Quelle: custom_components/epex_spot/SourceShell.py:121
Integration: EPEX Spot (Dokumentation, Probleme)
Erstmals aufgetreten: 00:00:00 (14 Vorkommnisse)
Zuletzt protokolliert: 11:03:37

no data found for <custom_components.epex_spot.EPEXSpot.SMARD.SMARD object at 0x7fa9e86e4f20>
no data found for <custom_components.epex_spot.EPEXSpot.SMARD.SMARD object at 0x7fa9dcdc4320>
no data found for <custom_components.epex_spot.EPEXSpot.SMARD.SMARD object at 0x7fa9d976f1a0>
no data found for <custom_components.epex_spot.EPEXSpot.SMARD.SMARD object at 0x7fa9e2289fd0>

**Comment by mampfes** [comment] 2024-09-06 18:48
Typically, these outages occur because the service is temporarily unavailable.
I will close this issue for now.
If the problem persists and is not caused by an outage of the service you can open it again.

**Closed by mampfes** 2024-09-06 18:48 UTC
