### ISSUE TITLE
Not seeing TOMORROW's data ?!

### ISSUE THREAD

**Issue by iz3man** [mampfes/ha_epex_spot#134] opened 2024-06-15 15:07 UTC
Any idea what could go wrong, as I'm not seeing tomorrow's data. I'm pretty sure it once was available. Can't really say what changed.
Data source is smartenergy.at

![image](https://github.com/mampfes/ha_epex_spot/assets/11553674/cfd8b80b-dbb6-4edc-8135-256e49f02cd7)

And this is the apex card's code (basically from the docs with some slight changes):

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: ct/kWh
graph_span: 32h
apex_config:
  legend:
    show: false
span:
  start: day
now:
  show: true
  label: Now
yaxis:
  - min: -15
    max: 40
    decimals: 0
    apex_config:
      tickAmount: 4
series:
  - entity: sensor.epex_spot_data_net_price
    name: Strompreis ct/kWh
    type: line
    show:
      extremas: true
    unit: ct/kWh
    data_generator: >
      return entity.attributes.data.map((entry, index) => { return [new
      Date(entry.start_time).getTime(), entry.price_ct_per_kwh]; });
    color_threshold:
      - value: 40
        color: '#ff0000'
      - value: 30
        color: '#facb23'
      - value: 20
        color: '#ffff00'
      - value: 0
        color: '#00ff00'
  - entity: sensor.epex_spot_data_price
    name: Strompreis ct/kWh
    type: column
    extend_to: end
    show:
      extremas: true
    unit: ct/kWh
    data_generator: >
      return entity.attributes.data.map((entry, index) => { return [new
      Date(entry.start_time).getTime(), entry.price_ct_per_kwh]; });
    color_threshold:
      - value: 20
        color: '#ff0000'
      - value: 15
        color: '#facb23'
      - value: 8
        color: '#ffff00'
      - value: 0
        color: '#00ff00'

```

**Comment by dodgydd** [comment] 2024-06-15 19:26
The GB feed also not working, I suspect it's to do with EPEX recent downtime and they came back up with a slightly different URL

**Comment by scirocco-berlin** [comment] 2024-07-02 07:48
After deactivation EPXSpot integration (DE) cannot be reactivated. Eroor message says:

![image](https://github.com/mampfes/ha_epex_spot/assets/165803350/a3589702-507a-4159-b769-446990d02c49)

**Comment by aquist-new** [comment] 2024-07-02 11:29
Same 403 for NL market.
![Screenshot 2024-07-02 at 13 29 00](https://github.com/mampfes/ha_epex_spot/assets/60740610/bee0f272-4625-4044-97c6-468eb5d4db50)

**Comment by mampfes** [comment] 2024-07-02 20:11
Did you already update to the latest release 2.3.8?

**Comment by aquist-new** [comment] 2024-07-03 07:13
Thanks. I just updated from 2.3.2 -> 2.3.8, and everything works again. Sorry for the confusion.

**Comment by martin-at-schorsch** [comment] 2024-07-18 13:45
I use release 2.3.8 and can confirm that next day data from smartenergy.at is not available, but Awattar (at) is.
![image](https://github.com/user-attachments/assets/a949ddd9-ba58-47af-9857-bd6aa82e1bfb)
(Second chart is smartenergy, third is Awattar)

**Comment by iz3man** [comment] 2024-07-18 14:16
Yep. Still the same here. No data with smartenergy for tomorrow. :(

**Comment by FlensGo** [comment] 2024-08-11 19:22
The Tibber source also doesn't show tomorrow's values.

**Comment by martin-at-schorsch** [comment] 2024-08-12 08:59
I've been using the Austrian data for some time now; Awattar seems to be the most reliable. SmartEnergy API has had outages several times now. From my point of view, it's clearly a problem with the data source, so this plugin cannot do anything about it.

**Comment by mampfes** [comment] 2024-08-15 17:38
This issue contains reports from multiple sources now. Typically problems with missing data are caused by outages in the service provider APIs. Therefore I will close this issue.
If there are new problems, please open a provider specific issue.

**Closed by mampfes** 2024-08-15 17:38 UTC
